package:
  name: skyfield
  version: "1.0"

source:
  fn: skyfield-1.0.tar.gz
  url: https://pypi.python.org/packages/22/9d/40a05ae85152f7908877063b204d4c23a0bd1a7b1c677b816b9facb54909/skyfield-1.0.tar.gz
  md5: b705ae38615cf8fd361fba616336fb1a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - skyfield = skyfield:main
    #
    # Would create an entry point called skyfield that calls skyfield.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - jplephem >=2.3
    - numpy
    - sgp4 >=1.4

  run:
    - python
    - jplephem >=2.3
    - numpy
    - sgp4 >=1.4

test:
  # Python imports
  imports:
    - skyfield
    - skyfield.data
    - skyfield.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/brandon-rhodes/python-skyfield/
  license: MIT License
  summary: 'Elegant astronomy for Python'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
